const AUTH_GET_TOKEN = 'AUTH_GET_TOKEN';
const AUTH_SAVE_TOKEN = 'AUTH_SAVE_TOKEN';
const AUTH_REMOVE_TOKEN = 'AUTH_REMOVE_TOKEN';
const AUTH_LOADING = 'AUTH_LOADING';
const AUTH_ERROR = 'ERROR';

export {
    AUTH_GET_TOKEN,
    AUTH_SAVE_TOKEN,
    AUTH_REMOVE_TOKEN,
    AUTH_LOADING,
    AUTH_ERROR
}
